[build]
  command = "npm run build"
  publish = "public"

[functions]
  directory = "netlify/functions"

[functions."predict"]
  schedule = "@hourly"

[[redirects]]
  from = "/api/latest"
  to = "/.netlify/functions/latest"
  status = 200
  force = true
